---
# tasks file for roles/deploy-compose-omero
- name: Initialize the deploy root and gather facts
  file: path={{ deploy_root }}/{{ item }} state=directory
  with_items:
    - shared
    - releases
    - releases/{{ docker_tag }}

- name: create self-signed SSL cert for Nginx
  command: openssl req -new -nodes -x509 -subj "{{ cert_subject }}" -days 3650 -keyout {{ key_file }} -out {{ cert_file }} -extensions v3_ca
  args:
    creates: "{{ cert_file }}"

- name: change permissions of key file
  file: path={{ key_file }}
        mode=0600


- name: clone deployment files shared between releases
  template: src={{ item }} dest={{ deploy_root }}/shared/{{ item }}
  with_items:
    - secrets.ejson
    - hyldapConfig.xml
    - make_env.sh

- name: clone deployment files of new release
  template: src={{ item }} dest={{ deploy_root }}/releases/{{ docker_tag }}/{{ item }}
  with_items:
    - docker-compose.yml

- name: edit hyldapConfig.xml
  xml:
    file: "{{ deploy_root }}/shared/hyldapConfig.xml"
    xpath: "/hyldapconfig"
    pretty_print: True
    add_children: "{{ allowed_groups }}"
  tags:
    - update_allowed_groups

- name: install init script
  template: src=omero-init-script
            dest=/etc/init.d/{{ service_name }}
            backup=no
            mode=0755


#- name: start service
#  service: name={{ service_name }} state=restarted
