---
# tasks file for roles/deploy-compose-omero

- name: create deployment directory and subdir for certs
  file: path={{ deploy_dir }}/nginx_auth state=directory

- name: clone deployment files
  template: src={{ item }} dest={{ deploy_dir }}/{{ item }}
  with_items:
    - secrets.ejson
    - make_env.sh
    - hyldapConfig.xml
    - docker-compose.yml

- name: install Python bindings to libxml
  apt: name=python-lxml state=present

- name: edit hyldapConfig.xml
  xml: 
    file: "{{ deploy_dir }}/hyldapConfig.xml"
    xpath: "/hyldapconfig"
    pretty_print: True
    add_children: "{{ allowed_groups }}"
 
- name: install init script
  template: src=omero-init-script 
            dest=/etc/init.d/{{ service_name }} 
            backup=no 
            mode=0755

- name: create self-signed SSL cert for Nginx
  command: openssl req -new -nodes -x509 -subj "{{ cert_subject }}" -days 3650 -keyout {{ deploy_dir }}/nginx_auth/server.key -out {{ deploy_dir }}/nginx_auth/server.crt -extensions v3_ca creates={{ deploy_dir }}/nginx_auth/server.crt

- name: copy key for nginx-proxy
  command: cp {{ deploy_dir }}/nginx_auth/server.key {{ key_file }}

- name: copy certificate for nginx-proxy
  command: cp {{ deploy_dir }}/nginx_auth/server.crt {{ cert_file }}

- name: start service
  service: name={{ service_name }} state=restarted

