initdb:
  image: {{ docker_owner }}/omero-initdb:{{ docker_tag }}
  environment:
    OMERO_ROOT_PASSWORD:

db:
  image: {{ docker_owner }}/omero-postgres:{{ docker_tag }}
  environment:
    POSTGRES_PASSWORD:
    DB_PASSWORD_OMERO:
    OMERO_ROOT_PASSWORD:
  volumes:
   - {{ volume_pgsql }}:/var/lib/postgresql/data:rw
   - {{ volume_pg_dump }}:/pg_dump:rw
  volumes_from:
   - initdb

omero:
  image: {{ docker_owner }}/omero-hyldap:{{ docker_tag }}
  environment:
    DB_PASSWORD_OMERO:
    OMERO_TRUSTSTORE_PASSWORD:
    LDAP_HOST: "{{ ldap_host }}"
    LDAP_PORT: "{{ ldap_port }}"
  links:
   - db
  expose:
   - "4064"
  volumes:
   - {{ deploy_root }}/shared/hyldapConfig.xml:/home/omero/hyldapConfig.xml
   - {{ volume_data_omero }}:/data/OMERO
  ports:
   - "{{ host_port_omero1 }}:4063"
   - "{{ host_port_omero2 }}:4064"

omeroweb:
  image: {{ docker_owner }}/omero-web:{{ docker_tag }}
  links:
   - omero
  expose:
   - "4080"

nginx:
  image: {{ docker_owner }}/omero-nginx:{{ docker_tag }}
  links:
   - omeroweb
  volumes_from:
   - omeroweb
  volumes:
   - {{ key_file }}:/etc/nginx/auth/server.key
   - {{ cert_file }}:/etc/nginx/auth/server.crt
  environment:
    VIRTUAL_HOST: "{{ virtual_host }}"
    VIRTUAL_PROTO: "https"
    VIRTUAL_PORT: 443
#  ports:
#   - "8080:80"
#   - "8443:443"
