#!/bin/sh
### BEGIN INIT INFO
# Provides: {{ service_name }}
# Required-Start: $local_fs $network $named $time $syslog docker
# Required-Stop: $local_fs $network $named $time $syslog docker
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: <DESCRIPTION>
### END INIT INFO

SHARED_DIR="{{ deploy_root }}/shared"
DEPLOY_DIR="{{ deploy_root }}/releases/{{ docker_tag }}"
PROJECT="{{ project_name }}"

ENV_FILE="${SHARED_DIR}/make_env.sh"
COMPOSE="${DEPLOY_DIR}/docker-compose.yml"

CMDBASE=". ${ENV_FILE} ; docker-compose -f $COMPOSE -p $PROJECT"
START="${CMDBASE} up -d"
STARTDB="${CMDBASE} up initdb; ${CMDBASE} up -d db"
STOP="${CMDBASE} stop"

RUNAS=root

start() {
echo 'Starting service…' >&2
echo "$START" >&2
su -c "$START" $RUNAS
echo 'Service started' >&2
}

startdb() {
echo 'Starting database…' >&2
echo "$STARTDB" >&2
su -c "$STARTDB" $RUNAS
echo 'Database started' >&2
}

stop() {
echo 'Stopping service…' >&2
su -c "$STOP" $RUNAS
echo 'Service stopped' >&2
}

case "$1" in
start)
start
;;
startdb)
startdb
;;
stop)
stop
;;
restart)
stop
start
;;
*)
echo "Usage: $0 {start|startdb|stop|restart}"
esac


